worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream backends {
        server 10.7.28.44:3001;
        server 10.7.31.67:3002;
    }

    server {
        listen 8080;
        server_name app.team1.test;

        location / {
            proxy_pass http://backends;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 8443 ssl;
        server_name app.team1.test;

        ssl_certificate /opt/homebrew/etc/nginx/tls/app.team1.test.crt;
        ssl_certificate_key /opt/homebrew/etc/nginx/tls/app.team1.test.key;

        location / {
            proxy_pass http://backends;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}